const Data = [
  {
    id: "1",
    image: "img/product-1.jpg",
    img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
    status: "HOT",
  },

  {
    id: "2",
    image: "img/product-2.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "SOFT LEATHER BELT",
    description: "bLACK LEATHER BELT",
    price: "48.00",
  },
  {
    id: "3",
    image: "img/product-3.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
    status: "HOT",
  },
  {
    id: "4",
    image: "img/product-4.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
  },
  {
    id: "5",
    image: "img/decor-1.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
  },
  {
    id: "6",
    image: "img/decor-2.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
  },
  {
    id: "7",
    image: "img/decor-3.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
    status: "HOT",
  },
  {
    id: "8",
    image: "img/decor-4.jpg",
     img: ["img/product-1.jpg", "img/product-4.jpg", "img/product-3.jpg","img/profile.jpg"],
    title: "WATCHES,HEADPHONE",
    description: "Black Grey Headset",
    price: "48.00",
    status: "HOT",
  },
];
export default Data;
